In [2]:
import pandas as pd

In [64]:
df = pd.read_csv('book.csv')

In [65]:
df

,Company,Fiscal Year,Total Revenue (in M),Net Income (in M),Total Assets (in M),Total Liabilities (in M ),Operating Cash Flow (in M)
0,Microsoft,2025,"281,724","101,832","619,003","275,524","136,162"
1,Microsoft,2024,"245,122","88,136","512,163","243,686","118,548"
2,Microsoft,2023,"211,915","72,361","411,976","205,753","87,582"
3,Tesla,2025,"94,827","3,855","137,806","54,941","14,747 \t"
4,Tesla,2024,"97,690","7,153","122,070","48,390","14,923"
5,Tesla,2023,"96,773","14,974","106,618","43,009","13,256"
6,Apple,2025,"416,161","112,010","359,241","285,508","111,482"
7,Apple,2024,"391,035","93,736","364,980","308,030","118,254"
8,Apple,2023,"383,285","96,995","352,583","290,437","110,543"

In [75]:
df.dtypes

Company                       object
Fiscal Year                    int64
 Total Revenue (in M)         object
Net Income (in M)             object
Total Assets (in M)           object
Total Liabilities (in M )     object
Operating Cash Flow (in M)    object
dtype: object

In [78]:
df.columns = df.columns.str.strip()

In [79]:
df.dtypes

Company                       object
Fiscal Year                    int64
Total Revenue (in M)          object
Net Income (in M)             object
Total Assets (in M)           object
Total Liabilities (in M )     object
Operating Cash Flow (in M)    object
dtype: object

In [80]:
df["Total Revenue (in M)"] = (
    df["Total Revenue (in M)"]
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [81]:
df["Net Income (in M)"] = (
    df["Net Income (in M)"]
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [82]:
df

,Company,Fiscal Year,Total Revenue (in M),Net Income (in M),Total Assets (in M),Total Liabilities (in M ),Operating Cash Flow (in M)
0,Microsoft,2025,281724.0,101832.0,"619,003","275,524","136,162"
1,Microsoft,2024,245122.0,88136.0,"512,163","243,686","118,548"
2,Microsoft,2023,211915.0,72361.0,"411,976","205,753","87,582"
3,Tesla,2025,94827.0,3855.0,"137,806","54,941","14,747 \t"
4,Tesla,2024,97690.0,7153.0,"122,070","48,390","14,923"
5,Tesla,2023,96773.0,14974.0,"106,618","43,009","13,256"
6,Apple,2025,416161.0,112010.0,"359,241","285,508","111,482"
7,Apple,2024,391035.0,93736.0,"364,980","308,030","118,254"
8,Apple,2023,383285.0,96995.0,"352,583","290,437","110,543"

In [84]:
df["Revenue Growth (%)"] = (
    df.groupby("Company")["Total Revenue (in M)"]
    .pct_change(fill_method=None) * 100
)

In [85]:
df["Net Income Growth (%)"] = (
    df.groupby("Company")["Net Income (in M)"]
    .pct_change(fill_method=None) * 100
)

In [86]:
df

,Company,Fiscal Year,Total Revenue (in M),Net Income (in M),Total Assets (in M),Total Liabilities (in M ),Operating Cash Flow (in M),Revenue Growth (%),Net Income Growth (%)
0,Microsoft,2025,281724.0,101832.0,"619,003","275,524","136,162",NaN,NaN
1,Microsoft,2024,245122.0,88136.0,"512,163","243,686","118,548",-12.992148,-13.449603
2,Microsoft,2023,211915.0,72361.0,"411,976","205,753","87,582",-13.547132,-17.898475
3,Tesla,2025,94827.0,3855.0,"137,806","54,941","14,747 \t",NaN,NaN
4,Tesla,2024,97690.0,7153.0,"122,070","48,390","14,923",3.019182,85.551232
5,Tesla,2023,96773.0,14974.0,"106,618","43,009","13,256",-0.938684,109.338739
6,Apple,2025,416161.0,112010.0,"359,241","285,508","111,482",NaN,NaN
7,Apple,2024,391035.0,93736.0,"364,980","308,030","118,254",-6.037567,-16.314615
8,Apple,2023,383285.0,96995.0,"352,583","290,437","110,543",-1.981920,3.476786

In [88]:
df.groupby("Company")["Total Revenue (in M)"].mean()

Company
Apple        396827.000000
Microsoft    246253.666667
Tesla         96430.000000
Name: Total Revenue (in M), dtype: float64

In [90]:
df.groupby("Fiscal Year")["Total Revenue (in M)"].sum()

Fiscal Year
2023    691973.0
2024    733847.0
2025    792712.0
Name: Total Revenue (in M), dtype: float64

In [91]:
df.groupby("Company")["Revenue Growth (%)"].mean()

Company
Apple        -4.009743
Microsoft   -13.269640
Tesla         1.040249
Name: Revenue Growth (%), dtype: float64

Financial Data Analysis

. REVENUE ANALYSIS
Apple has the highest revenue followed by Microsoft and then Tesla.

. NET INCOME ANALYSIS
Tesla has the highest net income followed by Apple and then Microsoft.

OBSERVATIONS

. Microsoft
Revenue and Net income declined consistently.
. Apple
Relatively stable revenue but fluctuating profitability
. Tesla
Experienced strong profit growth